/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'itinerary-pages': ItineraryPage;
    'accommodation-pages': AccommodationPage;
    'destination-pages': DestinationPage;
    'experience-pages': ExperiencePage;
    gallery: Gallery;
    testimonials: Testimonial;
    maldives: Maldive;
    blog: Blog;
    'trip-configuration': TripConfiguration;
    'vehicle-configuration': VehicleConfiguration;
    'visiting-places': VisitingPlace;
    drivers: Driver;
    guides: Guide;
    hotels: Hotel;
    'tour-requests': TourRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'itinerary-pages': ItineraryPagesSelect<false> | ItineraryPagesSelect<true>;
    'accommodation-pages': AccommodationPagesSelect<false> | AccommodationPagesSelect<true>;
    'destination-pages': DestinationPagesSelect<false> | DestinationPagesSelect<true>;
    'experience-pages': ExperiencePagesSelect<false> | ExperiencePagesSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    maldives: MaldivesSelect<false> | MaldivesSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    'trip-configuration': TripConfigurationSelect<false> | TripConfigurationSelect<true>;
    'vehicle-configuration': VehicleConfigurationSelect<false> | VehicleConfigurationSelect<true>;
    'visiting-places': VisitingPlacesSelect<false> | VisitingPlacesSelect<true>;
    drivers: DriversSelect<false> | DriversSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    hotels: HotelsSelect<false> | HotelsSelect<true>;
    'tour-requests': TourRequestsSelect<false> | TourRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  fullName: string;
  role: 'admin' | 'editor' | 'user';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alt text for the image (auto-generated from filename if not provided)
   */
  alt?: string | null;
  /**
   * Public URL of the image stored in Cloudinary
   */
  publicUrl?: string | null;
  /**
   * Cloudinary public ID for the image
   */
  cloudinaryPublicId?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "itinerary-pages".
 */
export interface ItineraryPage {
  id: string;
  /**
   * Select the itinerary category for this tour
   */
  category:
    | 'adventure-nature-based-tours'
    | 'culture-heritage-tours'
    | 'family-tours'
    | 'luxury-bespoke-tours'
    | 'north-east-coast-tours'
    | 'popular-tours'
    | 'purpose-built-tours'
    | 'romantic-tours'
    | 'special-transit-tours'
    | 'sports-based-tours'
    | 'sustainable-tours'
    | 'wellness-tours'
    | 'wildlife-tours';
  /**
   * The title of the tour (English - used as default)
   */
  title: string;
  /**
   * Translations for the tour title
   */
  titleTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * Small description for the tour card (English - used as default)
   */
  description: string;
  /**
   * Translations for the tour description
   */
  descriptionTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * Duration of the tour (e.g., "5 days", "3 days") - English
   */
  duration: string;
  /**
   * Translations for the tour duration
   */
  durationTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * Tour card image
   */
  image: string | Media;
  /**
   * Main hero image for the tour detail page (landscape orientation, not portrait)
   */
  mainImage?: (string | null) | Media;
  /**
   * URL-friendly slug for navigation (e.g., "mountain-trekking-expedition")
   */
  slug: string;
  /**
   * Full description shown on the tour detail page (English - used as default)
   */
  fullDescription?: string | null;
  /**
   * Translations for the full description
   */
  fullDescriptionTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * Add day-by-day itinerary for this tour
   */
  itineraryDays?:
    | {
        /**
         * Day number (e.g., 1, 2, 3)
         */
        dayNumber: number;
        /**
         * Day title (e.g., "BIA to Negombo") - English
         */
        title: string;
        /**
         * Translations for the day title
         */
        titleTranslations?: {
          de?: string | null;
          fr?: string | null;
          nl?: string | null;
          it?: string | null;
          es?: string | null;
          ru?: string | null;
        };
        /**
         * Activities for this day (English)
         */
        activities: {
          /**
           * Activity description in English
           */
          activity: string;
          /**
           * Translations for this activity
           */
          translations?: {
            de?: string | null;
            fr?: string | null;
            nl?: string | null;
            it?: string | null;
            es?: string | null;
            ru?: string | null;
          };
          id?: string | null;
        }[];
        /**
         * Images for this day (can add multiple)
         */
        images?:
          | {
              image: string | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accommodation-pages".
 */
export interface AccommodationPage {
  id: string;
  /**
   * The title of the accommodation (English - used as default)
   */
  title: string;
  /**
   * Translations for the accommodation title
   */
  titleTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * Description for the accommodation card (English - used as default)
   */
  description: string;
  /**
   * Translations for the accommodation description
   */
  descriptionTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * Location of the accommodation (e.g., "Colombo", "Kandy")
   */
  location?: string | null;
  /**
   * Translations for the location
   */
  locationTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * Accommodation card image
   */
  image: string | Media;
  /**
   * Main hero image for the accommodation detail page
   */
  mainImage?: (string | null) | Media;
  /**
   * URL-friendly slug for navigation (e.g., "luxury-beach-resort")
   */
  slug: string;
  /**
   * Full description shown on the accommodation detail page (English - used as default)
   */
  fullDescription?: string | null;
  /**
   * Translations for the full description
   */
  fullDescriptionTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * Number of rooms (e.g., 13)
   */
  numberOfRooms?: number | null;
  /**
   * Number of restaurants (e.g., 1)
   */
  numberOfRestaurants?: number | null;
  /**
   * Management company (e.g., "Nyne Hotels")
   */
  managedBy?: string | null;
  /**
   * Translations for the management company
   */
  managedByTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * List of facilities/amenities (e.g., "Free Wifi", "Restaurant", "Free parking")
   */
  facilities?:
    | {
        /**
         * Facility name (English)
         */
        facility: string;
        /**
         * Translations for this facility
         */
        translations?: {
          de?: string | null;
          fr?: string | null;
          nl?: string | null;
          it?: string | null;
          es?: string | null;
          ru?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Add different room types available at this accommodation
   */
  roomTypes?:
    | {
        /**
         * Room type name (e.g., "Superior King Room") - English
         */
        roomName: string;
        /**
         * Translations for the room name
         */
        roomNameTranslations?: {
          de?: string | null;
          fr?: string | null;
          nl?: string | null;
          it?: string | null;
          es?: string | null;
          ru?: string | null;
        };
        /**
         * Room description (English)
         */
        roomDescription?: string | null;
        /**
         * Translations for the room description
         */
        roomDescriptionTranslations?: {
          de?: string | null;
          fr?: string | null;
          nl?: string | null;
          it?: string | null;
          es?: string | null;
          ru?: string | null;
        };
        /**
         * Room image
         */
        roomImage?: (string | null) | Media;
        /**
         * Room size (e.g., "21 m²")
         */
        roomSize?: string | null;
        /**
         * List of room features/amenities
         */
        roomFeatures?:
          | {
              /**
               * Feature name (English)
               */
              feature: string;
              /**
               * Translations for this feature
               */
              translations?: {
                de?: string | null;
                fr?: string | null;
                nl?: string | null;
                it?: string | null;
                es?: string | null;
                ru?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destination-pages".
 */
export interface DestinationPage {
  id: string;
  /**
   * The title of the destination (English - used as default)
   */
  title: string;
  /**
   * Translations for the destination title
   */
  titleTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * Description for the destination card (English - used as default)
   */
  description: string;
  /**
   * Translations for the destination description
   */
  descriptionTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * Full description for the destination detail page (English - used as default)
   */
  fullDescription?: string | null;
  /**
   * Translations for the full description
   */
  fullDescriptionTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * URL-friendly identifier (e.g., "colombo", "kandy")
   */
  slug: string;
  /**
   * Destination card image
   */
  image: string | Media;
  /**
   * Main image for destination detail page (curved image on left)
   */
  mainImage?: (string | null) | Media;
  /**
   * List of top attractions for this destination
   */
  topAttractions?:
    | {
        /**
         * Attraction name (English)
         */
        attractionName: string;
        /**
         * Translations for this attraction name
         */
        attractionNameTranslations?: {
          de?: string | null;
          fr?: string | null;
          nl?: string | null;
          it?: string | null;
          es?: string | null;
          ru?: string | null;
        };
        /**
         * Attraction description (English)
         */
        attractionDescription?: string | null;
        /**
         * Translations for this attraction description
         */
        attractionDescriptionTranslations?: {
          de?: string | null;
          fr?: string | null;
          nl?: string | null;
          it?: string | null;
          es?: string | null;
          ru?: string | null;
        };
        /**
         * Attraction image
         */
        attractionImage?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience-pages".
 */
export interface ExperiencePage {
  id: string;
  /**
   * The title of the experience (English - used as default)
   */
  title: string;
  /**
   * Translations for the experience title
   */
  titleTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * Description for the experience card (English - used as default)
   */
  description: string;
  /**
   * Translations for the experience description
   */
  descriptionTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * Full description for the experience detail page (English - used as default)
   */
  fullDescription?: string | null;
  /**
   * Translations for the full description
   */
  fullDescriptionTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * URL-friendly identifier (e.g., "ayubowan-welcome", "tea-ceremony")
   */
  slug: string;
  /**
   * Experience card image
   */
  image: string | Media;
  /**
   * Main image for experience detail page (curved image on left)
   */
  mainImage?: (string | null) | Media;
  /**
   * List of locations where this experience can be enjoyed
   */
  whereYouCanExperience?:
    | {
        /**
         * Location title (English)
         */
        title: string;
        /**
         * Translations for this location title
         */
        titleTranslations?: {
          de?: string | null;
          fr?: string | null;
          nl?: string | null;
          it?: string | null;
          es?: string | null;
          ru?: string | null;
        };
        /**
         * Location description (English)
         */
        description: string;
        /**
         * Translations for this location description
         */
        descriptionTranslations?: {
          de?: string | null;
          fr?: string | null;
          nl?: string | null;
          it?: string | null;
          es?: string | null;
          ru?: string | null;
        };
        /**
         * Location image
         */
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: string;
  /**
   * Upload an image for the gallery
   */
  image: string | Media;
  /**
   * Alt text for the image (for accessibility)
   */
  alt: string;
  /**
   * Order in which the image should appear (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  /**
   * The testimonial title (English - used as default)
   */
  title: string;
  /**
   * Translations for the testimonial title
   */
  titleTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * The customer feedback/testimonial (English - used as default)
   */
  feedback: string;
  /**
   * Translations for the customer feedback
   */
  feedbackTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * Customer name (English - used as default)
   */
  customerName: string;
  /**
   * Translations for the customer name (if needed)
   */
  customerNameTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * Order in which the testimonial should appear (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maldives".
 */
export interface Maldive {
  id: string;
  /**
   * Select the type of itinerary
   */
  type: 'maldives' | 'maldives-sri-lanka';
  /**
   * The title of the Maldives package (English - used as default)
   */
  title: string;
  /**
   * Translations for the package title
   */
  titleTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * Short description of the package (English - used as default)
   */
  description: string;
  /**
   * Translations for the package description
   */
  descriptionTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * Full detailed description for the detail page (English - used as default)
   */
  fullDescription?: string | null;
  /**
   * Translations for the full description
   */
  fullDescriptionTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * Duration of the package (e.g., "12 Days", "4 Days")
   */
  duration: string;
  /**
   * Location (e.g., "Maldives", "Sri Lanka + Maldives")
   */
  location: string;
  /**
   * Main image for the package card
   */
  image: string | Media;
  /**
   * Hero image for the detail page (optional)
   */
  heroImage?: (string | null) | Media;
  /**
   * URL-friendly identifier (e.g., "sri-lanka-maldives-honeymoon-tour")
   */
  slug: string;
  /**
   * Day-by-day itinerary
   */
  itineraryDays?:
    | {
        /**
         * Day number (1, 2, 3, etc.)
         */
        dayNumber: number;
        /**
         * Day title (e.g., "BIA to Kotugoda")
         */
        title: string;
        titleTranslations?: {
          de?: string | null;
          fr?: string | null;
          nl?: string | null;
          it?: string | null;
          es?: string | null;
          ru?: string | null;
        };
        activities?:
          | {
              activity: string;
              translations?: {
                de?: string | null;
                fr?: string | null;
                nl?: string | null;
                it?: string | null;
                es?: string | null;
                ru?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        images?:
          | {
              image?: (string | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: string;
  /**
   * The title of the blog post (English - used as default)
   */
  title: string;
  /**
   * Translations for the blog post title
   */
  titleTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * Author name for the blog post
   */
  author: string;
  /**
   * Publication date of the blog post
   */
  publishedDate: string;
  /**
   * Short excerpt/summary of the blog post (English - used as default)
   */
  excerpt: string;
  /**
   * Translations for the blog post excerpt
   */
  excerptTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * Full content of the blog post (English - used as default)
   */
  content: string;
  /**
   * Translations for the blog post content
   */
  contentTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * Featured image for the blog post
   */
  image: string | Media;
  /**
   * URL-friendly slug for the blog post (e.g., "blog-post-title")
   */
  slug: string;
  /**
   * Order for sorting blog posts (higher numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Default configuration for trip planning calculations. Only one configuration document should exist.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trip-configuration".
 */
export interface TripConfiguration {
  id: string;
  /**
   * Configuration name (for reference)
   */
  name: string;
  /**
   * Default stay time in one place (in minutes)
   */
  stayTimeInMinutes: number;
  /**
   * Default traveling hours per day
   */
  travelingHoursPerDay: number;
  /**
   * Default cost to visit/stay at a place in Sri Lankan Rupees (LKR)
   */
  defaultStayCost: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Vehicle configurations with pricing per kilometer
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-configuration".
 */
export interface VehicleConfiguration {
  id: string;
  /**
   * Type of vehicle (e.g., Car, Van, Bus, SUV)
   */
  vehicleType: string;
  /**
   * Maximum number of passengers the vehicle can accommodate
   */
  passengerCount: number;
  /**
   * LKR (Sri Lankan Rupees) cost per one kilometer for this vehicle
   */
  lkrPerKilometer: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage visiting places that can be selected for trip planning
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visiting-places".
 */
export interface VisitingPlace {
  id: string;
  /**
   * Name of the visiting place
   */
  name: string;
  /**
   * Latitude coordinate of the place (must be within Sri Lanka: 5.9 to 9.8)
   */
  latitude: number;
  /**
   * Longitude coordinate of the place (must be within Sri Lanka: 79.7 to 81.9)
   */
  longitude: number;
  /**
   * Duration to stay at this place in minutes (e.g., 60 for 1 hour)
   */
  stayDuration?: number | null;
  /**
   * Cost to visit/stay at this place in Sri Lankan Rupees (LKR)
   */
  stayCost?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drivers".
 */
export interface Driver {
  id: string;
  /**
   * Full Name as per NIC/Passport
   */
  fullName: string;
  /**
   * NIC or Passport Number
   */
  nicPassportNumber: string;
  /**
   * Date of Birth
   */
  dateOfBirth: string;
  /**
   * Primary Contact Number
   */
  contactNumber: string;
  /**
   * WhatsApp Number (if different from contact number)
   */
  whatsappNumber?: string | null;
  /**
   * Email Address (Optional)
   */
  emailAddress?: string | null;
  /**
   * Residential Address
   */
  residentialAddress: string;
  /**
   * District/Province
   */
  district: string;
  /**
   * Emergency Contact Name
   */
  emergencyContactName: string;
  /**
   * Emergency Contact Number
   */
  emergencyContactNumber: string;
  /**
   * Profile Photo
   */
  profilePhoto?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: string;
  /**
   * Full Name as per NIC/Passport
   */
  fullName: string;
  /**
   * NIC or Passport Number
   */
  nicPassportNumber: string;
  /**
   * Date of Birth
   */
  dateOfBirth: string;
  /**
   * Primary Contact Number
   */
  contactNumber: string;
  /**
   * WhatsApp Number (if different from contact number)
   */
  whatsappNumber?: string | null;
  /**
   * Email Address (Optional)
   */
  emailAddress?: string | null;
  /**
   * Residential Address
   */
  residentialAddress: string;
  /**
   * District/Province
   */
  district: string;
  /**
   * Emergency Contact Name
   */
  emergencyContactName: string;
  /**
   * Emergency Contact Number
   */
  emergencyContactNumber: string;
  /**
   * Profile Photo
   */
  profilePhoto?: (string | null) | Media;
  /**
   * NIC Photo (Front)
   */
  nicPhotoFront?: (string | null) | Media;
  /**
   * NIC Photo (Back)
   */
  nicPhotoBack?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hotels".
 */
export interface Hotel {
  id: string;
  /**
   * Name of the hotel
   */
  hotelName: string;
  /**
   * Latitude coordinate of the hotel location
   */
  latitude: number;
  /**
   * Longitude coordinate of the hotel location
   */
  longitude: number;
  /**
   * Star rating of the hotel
   */
  starRating: '1' | '2' | '3' | '4' | '5';
  /**
   * Small description about the hotel (English - used as default)
   */
  description?: string | null;
  /**
   * Translations for the hotel description
   */
  descriptionTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  /**
   * Hotel images
   */
  images?:
    | {
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Add packages with room prices for this hotel
   */
  packages?:
    | {
        /**
         * Name of the package (e.g., "Standard Room", "Deluxe Suite")
         */
        packageName: string;
        /**
         * Price for one night in LKR
         */
        roomPricePerNight: number;
        /**
         * Description of what is included in this package
         */
        packageDescription?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour-requests".
 */
export interface TourRequest {
  id: string;
  /**
   * Type of service requested
   */
  type: 'driver' | 'guide';
  /**
   * ID of the driver or guide
   */
  driverOrGuideId: string;
  /**
   * Name of the driver or guide
   */
  driverOrGuideName: string;
  /**
   * Email of the driver or guide
   */
  driverOrGuideEmail?: string | null;
  /**
   * Contact number of the driver or guide
   */
  driverOrGuideContact: string;
  /**
   * Tourist name
   */
  touristName: string;
  /**
   * Tourist email
   */
  touristEmail: string;
  /**
   * Tourist contact number
   */
  touristContact: string;
  /**
   * Tour start date
   */
  startDate: string;
  /**
   * Tour end date
   */
  endDate: string;
  /**
   * Request status
   */
  status: 'pending' | 'done' | 'cancel';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'itinerary-pages';
        value: string | ItineraryPage;
      } | null)
    | ({
        relationTo: 'accommodation-pages';
        value: string | AccommodationPage;
      } | null)
    | ({
        relationTo: 'destination-pages';
        value: string | DestinationPage;
      } | null)
    | ({
        relationTo: 'experience-pages';
        value: string | ExperiencePage;
      } | null)
    | ({
        relationTo: 'gallery';
        value: string | Gallery;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'maldives';
        value: string | Maldive;
      } | null)
    | ({
        relationTo: 'blog';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'trip-configuration';
        value: string | TripConfiguration;
      } | null)
    | ({
        relationTo: 'vehicle-configuration';
        value: string | VehicleConfiguration;
      } | null)
    | ({
        relationTo: 'visiting-places';
        value: string | VisitingPlace;
      } | null)
    | ({
        relationTo: 'drivers';
        value: string | Driver;
      } | null)
    | ({
        relationTo: 'guides';
        value: string | Guide;
      } | null)
    | ({
        relationTo: 'hotels';
        value: string | Hotel;
      } | null)
    | ({
        relationTo: 'tour-requests';
        value: string | TourRequest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  publicUrl?: T;
  cloudinaryPublicId?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "itinerary-pages_select".
 */
export interface ItineraryPagesSelect<T extends boolean = true> {
  category?: T;
  title?: T;
  titleTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  description?: T;
  descriptionTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  duration?: T;
  durationTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  image?: T;
  mainImage?: T;
  slug?: T;
  fullDescription?: T;
  fullDescriptionTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  itineraryDays?:
    | T
    | {
        dayNumber?: T;
        title?: T;
        titleTranslations?:
          | T
          | {
              de?: T;
              fr?: T;
              nl?: T;
              it?: T;
              es?: T;
              ru?: T;
            };
        activities?:
          | T
          | {
              activity?: T;
              translations?:
                | T
                | {
                    de?: T;
                    fr?: T;
                    nl?: T;
                    it?: T;
                    es?: T;
                    ru?: T;
                  };
              id?: T;
            };
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accommodation-pages_select".
 */
export interface AccommodationPagesSelect<T extends boolean = true> {
  title?: T;
  titleTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  description?: T;
  descriptionTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  location?: T;
  locationTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  image?: T;
  mainImage?: T;
  slug?: T;
  fullDescription?: T;
  fullDescriptionTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  numberOfRooms?: T;
  numberOfRestaurants?: T;
  managedBy?: T;
  managedByTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  facilities?:
    | T
    | {
        facility?: T;
        translations?:
          | T
          | {
              de?: T;
              fr?: T;
              nl?: T;
              it?: T;
              es?: T;
              ru?: T;
            };
        id?: T;
      };
  roomTypes?:
    | T
    | {
        roomName?: T;
        roomNameTranslations?:
          | T
          | {
              de?: T;
              fr?: T;
              nl?: T;
              it?: T;
              es?: T;
              ru?: T;
            };
        roomDescription?: T;
        roomDescriptionTranslations?:
          | T
          | {
              de?: T;
              fr?: T;
              nl?: T;
              it?: T;
              es?: T;
              ru?: T;
            };
        roomImage?: T;
        roomSize?: T;
        roomFeatures?:
          | T
          | {
              feature?: T;
              translations?:
                | T
                | {
                    de?: T;
                    fr?: T;
                    nl?: T;
                    it?: T;
                    es?: T;
                    ru?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destination-pages_select".
 */
export interface DestinationPagesSelect<T extends boolean = true> {
  title?: T;
  titleTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  description?: T;
  descriptionTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  fullDescription?: T;
  fullDescriptionTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  slug?: T;
  image?: T;
  mainImage?: T;
  topAttractions?:
    | T
    | {
        attractionName?: T;
        attractionNameTranslations?:
          | T
          | {
              de?: T;
              fr?: T;
              nl?: T;
              it?: T;
              es?: T;
              ru?: T;
            };
        attractionDescription?: T;
        attractionDescriptionTranslations?:
          | T
          | {
              de?: T;
              fr?: T;
              nl?: T;
              it?: T;
              es?: T;
              ru?: T;
            };
        attractionImage?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience-pages_select".
 */
export interface ExperiencePagesSelect<T extends boolean = true> {
  title?: T;
  titleTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  description?: T;
  descriptionTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  fullDescription?: T;
  fullDescriptionTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  slug?: T;
  image?: T;
  mainImage?: T;
  whereYouCanExperience?:
    | T
    | {
        title?: T;
        titleTranslations?:
          | T
          | {
              de?: T;
              fr?: T;
              nl?: T;
              it?: T;
              es?: T;
              ru?: T;
            };
        description?: T;
        descriptionTranslations?:
          | T
          | {
              de?: T;
              fr?: T;
              nl?: T;
              it?: T;
              es?: T;
              ru?: T;
            };
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  image?: T;
  alt?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  title?: T;
  titleTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  feedback?: T;
  feedbackTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  customerName?: T;
  customerNameTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maldives_select".
 */
export interface MaldivesSelect<T extends boolean = true> {
  type?: T;
  title?: T;
  titleTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  description?: T;
  descriptionTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  fullDescription?: T;
  fullDescriptionTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  duration?: T;
  location?: T;
  image?: T;
  heroImage?: T;
  slug?: T;
  itineraryDays?:
    | T
    | {
        dayNumber?: T;
        title?: T;
        titleTranslations?:
          | T
          | {
              de?: T;
              fr?: T;
              nl?: T;
              it?: T;
              es?: T;
              ru?: T;
            };
        activities?:
          | T
          | {
              activity?: T;
              translations?:
                | T
                | {
                    de?: T;
                    fr?: T;
                    nl?: T;
                    it?: T;
                    es?: T;
                    ru?: T;
                  };
              id?: T;
            };
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title?: T;
  titleTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  author?: T;
  publishedDate?: T;
  excerpt?: T;
  excerptTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  content?: T;
  contentTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  image?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trip-configuration_select".
 */
export interface TripConfigurationSelect<T extends boolean = true> {
  name?: T;
  stayTimeInMinutes?: T;
  travelingHoursPerDay?: T;
  defaultStayCost?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-configuration_select".
 */
export interface VehicleConfigurationSelect<T extends boolean = true> {
  vehicleType?: T;
  passengerCount?: T;
  lkrPerKilometer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visiting-places_select".
 */
export interface VisitingPlacesSelect<T extends boolean = true> {
  name?: T;
  latitude?: T;
  longitude?: T;
  stayDuration?: T;
  stayCost?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drivers_select".
 */
export interface DriversSelect<T extends boolean = true> {
  fullName?: T;
  nicPassportNumber?: T;
  dateOfBirth?: T;
  contactNumber?: T;
  whatsappNumber?: T;
  emailAddress?: T;
  residentialAddress?: T;
  district?: T;
  emergencyContactName?: T;
  emergencyContactNumber?: T;
  profilePhoto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  fullName?: T;
  nicPassportNumber?: T;
  dateOfBirth?: T;
  contactNumber?: T;
  whatsappNumber?: T;
  emailAddress?: T;
  residentialAddress?: T;
  district?: T;
  emergencyContactName?: T;
  emergencyContactNumber?: T;
  profilePhoto?: T;
  nicPhotoFront?: T;
  nicPhotoBack?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hotels_select".
 */
export interface HotelsSelect<T extends boolean = true> {
  hotelName?: T;
  latitude?: T;
  longitude?: T;
  starRating?: T;
  description?: T;
  descriptionTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  packages?:
    | T
    | {
        packageName?: T;
        roomPricePerNight?: T;
        packageDescription?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour-requests_select".
 */
export interface TourRequestsSelect<T extends boolean = true> {
  type?: T;
  driverOrGuideId?: T;
  driverOrGuideName?: T;
  driverOrGuideEmail?: T;
  driverOrGuideContact?: T;
  touristName?: T;
  touristEmail?: T;
  touristContact?: T;
  startDate?: T;
  endDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}