/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    media: Media;
    'itinerary-pages': ItineraryPage;
    'accommodation-pages': AccommodationPage;
    'destination-pages': DestinationPage;
    'experience-pages': ExperiencePage;
    gallery: Gallery;
    testimonials: Testimonial;
    maldives: Maldive;
    blog: Blog;
    'trip-configuration': TripConfiguration;
    'vehicle-configuration': VehicleConfiguration;
    'visiting-places': VisitingPlace;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'itinerary-pages': ItineraryPagesSelect<false> | ItineraryPagesSelect<true>;
    'accommodation-pages': AccommodationPagesSelect<false> | AccommodationPagesSelect<true>;
    'destination-pages': DestinationPagesSelect<false> | DestinationPagesSelect<true>;
    'experience-pages': ExperiencePagesSelect<false> | ExperiencePagesSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    maldives: MaldivesSelect<false> | MaldivesSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    'trip-configuration': TripConfigurationSelect<false> | TripConfigurationSelect<true>;
    'vehicle-configuration': VehicleConfigurationSelect<false> | VehicleConfigurationSelect<true>;
    'visiting-places': VisitingPlacesSelect<false> | VisitingPlacesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  fullName: string;
  role: 'admin' | 'editor' | 'user';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "itinerary-pages".
 */
export interface ItineraryPage {
  id: string;
  category:
    | 'adventure-nature-based-tours'
    | 'culture-heritage-tours'
    | 'family-tours'
    | 'luxury-bespoke-tours'
    | 'north-east-coast-tours'
    | 'popular-tours'
    | 'purpose-built-tours'
    | 'romantic-tours'
    | 'special-transit-tours'
    | 'sports-based-tours'
    | 'sustainable-tours'
    | 'wellness-tours'
    | 'wildlife-tours';
  title: string;
  titleTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  description: string;
  descriptionTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  duration: string;
  durationTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  image: string | Media;
  mainImage?: (string | null) | Media;
  slug: string;
  fullDescription?: string | null;
  fullDescriptionTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  itineraryDays?:
    | {
        dayNumber: number;
        title: string;
        titleTranslations?: {
          de?: string | null;
          fr?: string | null;
          nl?: string | null;
          it?: string | null;
          es?: string | null;
          ru?: string | null;
        };
        activities: {
          activity: string;
          translations?: {
            de?: string | null;
            fr?: string | null;
            nl?: string | null;
            it?: string | null;
            es?: string | null;
            ru?: string | null;
          };
          id?: string | null;
        }[];
        images?:
          | {
              image: string | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accommodation-pages".
 */
export interface AccommodationPage {
  id: string;
  title: string;
  titleTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  description: string;
  descriptionTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  location?: string | null;
  locationTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  image: string | Media;
  mainImage?: (string | null) | Media;
  slug: string;
  fullDescription?: string | null;
  fullDescriptionTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  numberOfRooms?: number | null;
  numberOfRestaurants?: number | null;
  managedBy?: string | null;
  managedByTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  facilities?:
    | {
        facility: string;
        translations?: {
          de?: string | null;
          fr?: string | null;
          nl?: string | null;
          it?: string | null;
          es?: string | null;
          ru?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  roomTypes?:
    | {
        roomName: string;
        roomNameTranslations?: {
          de?: string | null;
          fr?: string | null;
          nl?: string | null;
          it?: string | null;
          es?: string | null;
          ru?: string | null;
        };
        roomDescription?: string | null;
        roomDescriptionTranslations?: {
          de?: string | null;
          fr?: string | null;
          nl?: string | null;
          it?: string | null;
          es?: string | null;
          ru?: string | null;
        };
        roomImage?: (string | null) | Media;
        roomSize?: string | null;
        roomFeatures?:
          | {
              feature: string;
              translations?: {
                de?: string | null;
                fr?: string | null;
                nl?: string | null;
                it?: string | null;
                es?: string | null;
                ru?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destination-pages".
 */
export interface DestinationPage {
  id: string;
  title: string;
  titleTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  description: string;
  descriptionTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  fullDescription?: string | null;
  fullDescriptionTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  slug: string;
  image: string | Media;
  mainImage?: (string | null) | Media;
  topAttractions?:
    | {
        attractionName: string;
        attractionNameTranslations?: {
          de?: string | null;
          fr?: string | null;
          nl?: string | null;
          it?: string | null;
          es?: string | null;
          ru?: string | null;
        };
        attractionDescription?: string | null;
        attractionDescriptionTranslations?: {
          de?: string | null;
          fr?: string | null;
          nl?: string | null;
          it?: string | null;
          es?: string | null;
          ru?: string | null;
        };
        attractionImage?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience-pages".
 */
export interface ExperiencePage {
  id: string;
  title: string;
  titleTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  description: string;
  descriptionTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  fullDescription?: string | null;
  fullDescriptionTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  slug: string;
  image: string | Media;
  mainImage?: (string | null) | Media;
  whereYouCanExperience?:
    | {
        title: string;
        titleTranslations?: {
          de?: string | null;
          fr?: string | null;
          nl?: string | null;
          it?: string | null;
          es?: string | null;
          ru?: string | null;
        };
        description: string;
        descriptionTranslations?: {
          de?: string | null;
          fr?: string | null;
          nl?: string | null;
          it?: string | null;
          es?: string | null;
          ru?: string | null;
        };
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: string;
  image: string | Media;
  alt: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  title: string;
  titleTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  feedback: string;
  feedbackTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  customerName: string;
  customerNameTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maldives".
 */
export interface Maldive {
  id: string;
  type: 'maldives' | 'maldives-sri-lanka';
  title: string;
  titleTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  description: string;
  descriptionTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  fullDescription?: string | null;
  fullDescriptionTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  duration: string;
  location: string;
  image: string | Media;
  heroImage?: (string | null) | Media;
  slug: string;
  itineraryDays?:
    | {
        dayNumber: number;
        title: string;
        titleTranslations?: {
          de?: string | null;
          fr?: string | null;
          nl?: string | null;
          it?: string | null;
          es?: string | null;
          ru?: string | null;
        };
        activities?:
          | {
              activity: string;
              translations?: {
                de?: string | null;
                fr?: string | null;
                nl?: string | null;
                it?: string | null;
                es?: string | null;
                ru?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        images?:
          | {
              image?: (string | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: string;
  title: string;
  titleTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  author: string;
  publishedDate: string;
  excerpt: string;
  excerptTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  content: string;
  contentTranslations?: {
    de?: string | null;
    fr?: string | null;
    nl?: string | null;
    it?: string | null;
    es?: string | null;
    ru?: string | null;
  };
  image: string | Media;
  slug: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trip-configuration".
 */
export interface TripConfiguration {
  id: string;
  name: string;
  stayTimeInMinutes: number;
  travelingHoursPerDay: number;
  defaultStayCost: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-configuration".
 */
export interface VehicleConfiguration {
  id: string;
  vehicleType: string;
  passengerCount: number;
  lkrPerKilometer: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visiting-places".
 */
export interface VisitingPlace {
  id: string;
  name: string;
  latitude: number;
  longitude: number;
  stayDuration?: number | null;
  stayCost?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'itinerary-pages';
        value: string | ItineraryPage;
      } | null)
    | ({
        relationTo: 'accommodation-pages';
        value: string | AccommodationPage;
      } | null)
    | ({
        relationTo: 'destination-pages';
        value: string | DestinationPage;
      } | null)
    | ({
        relationTo: 'experience-pages';
        value: string | ExperiencePage;
      } | null)
    | ({
        relationTo: 'gallery';
        value: string | Gallery;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'maldives';
        value: string | Maldive;
      } | null)
    | ({
        relationTo: 'blog';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'trip-configuration';
        value: string | TripConfiguration;
      } | null)
    | ({
        relationTo: 'vehicle-configuration';
        value: string | VehicleConfiguration;
      } | null)
    | ({
        relationTo: 'visiting-places';
        value: string | VisitingPlace;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "itinerary-pages_select".
 */
export interface ItineraryPagesSelect<T extends boolean = true> {
  category?: T;
  title?: T;
  titleTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  description?: T;
  descriptionTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  duration?: T;
  durationTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  image?: T;
  mainImage?: T;
  slug?: T;
  fullDescription?: T;
  fullDescriptionTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  itineraryDays?:
    | T
    | {
        dayNumber?: T;
        title?: T;
        titleTranslations?:
          | T
          | {
              de?: T;
              fr?: T;
              nl?: T;
              it?: T;
              es?: T;
              ru?: T;
            };
        activities?:
          | T
          | {
              activity?: T;
              translations?:
                | T
                | {
                    de?: T;
                    fr?: T;
                    nl?: T;
                    it?: T;
                    es?: T;
                    ru?: T;
                  };
              id?: T;
            };
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accommodation-pages_select".
 */
export interface AccommodationPagesSelect<T extends boolean = true> {
  title?: T;
  titleTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  description?: T;
  descriptionTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  location?: T;
  locationTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  image?: T;
  mainImage?: T;
  slug?: T;
  fullDescription?: T;
  fullDescriptionTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  numberOfRooms?: T;
  numberOfRestaurants?: T;
  managedBy?: T;
  managedByTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  facilities?:
    | T
    | {
        facility?: T;
        translations?:
          | T
          | {
              de?: T;
              fr?: T;
              nl?: T;
              it?: T;
              es?: T;
              ru?: T;
            };
        id?: T;
      };
  roomTypes?:
    | T
    | {
        roomName?: T;
        roomNameTranslations?:
          | T
          | {
              de?: T;
              fr?: T;
              nl?: T;
              it?: T;
              es?: T;
              ru?: T;
            };
        roomDescription?: T;
        roomDescriptionTranslations?:
          | T
          | {
              de?: T;
              fr?: T;
              nl?: T;
              it?: T;
              es?: T;
              ru?: T;
            };
        roomImage?: T;
        roomSize?: T;
        roomFeatures?:
          | T
          | {
              feature?: T;
              translations?:
                | T
                | {
                    de?: T;
                    fr?: T;
                    nl?: T;
                    it?: T;
                    es?: T;
                    ru?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destination-pages_select".
 */
export interface DestinationPagesSelect<T extends boolean = true> {
  title?: T;
  titleTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  description?: T;
  descriptionTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  fullDescription?: T;
  fullDescriptionTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  slug?: T;
  image?: T;
  mainImage?: T;
  topAttractions?:
    | T
    | {
        attractionName?: T;
        attractionNameTranslations?:
          | T
          | {
              de?: T;
              fr?: T;
              nl?: T;
              it?: T;
              es?: T;
              ru?: T;
            };
        attractionDescription?: T;
        attractionDescriptionTranslations?:
          | T
          | {
              de?: T;
              fr?: T;
              nl?: T;
              it?: T;
              es?: T;
              ru?: T;
            };
        attractionImage?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience-pages_select".
 */
export interface ExperiencePagesSelect<T extends boolean = true> {
  title?: T;
  titleTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  description?: T;
  descriptionTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  fullDescription?: T;
  fullDescriptionTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  slug?: T;
  image?: T;
  mainImage?: T;
  whereYouCanExperience?:
    | T
    | {
        title?: T;
        titleTranslations?:
          | T
          | {
              de?: T;
              fr?: T;
              nl?: T;
              it?: T;
              es?: T;
              ru?: T;
            };
        description?: T;
        descriptionTranslations?:
          | T
          | {
              de?: T;
              fr?: T;
              nl?: T;
              it?: T;
              es?: T;
              ru?: T;
            };
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  image?: T;
  alt?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  title?: T;
  titleTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  feedback?: T;
  feedbackTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  customerName?: T;
  customerNameTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maldives_select".
 */
export interface MaldivesSelect<T extends boolean = true> {
  type?: T;
  title?: T;
  titleTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  description?: T;
  descriptionTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  fullDescription?: T;
  fullDescriptionTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  duration?: T;
  location?: T;
  image?: T;
  heroImage?: T;
  slug?: T;
  itineraryDays?:
    | T
    | {
        dayNumber?: T;
        title?: T;
        titleTranslations?:
          | T
          | {
              de?: T;
              fr?: T;
              nl?: T;
              it?: T;
              es?: T;
              ru?: T;
            };
        activities?:
          | T
          | {
              activity?: T;
              translations?:
                | T
                | {
                    de?: T;
                    fr?: T;
                    nl?: T;
                    it?: T;
                    es?: T;
                    ru?: T;
                  };
              id?: T;
            };
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title?: T;
  titleTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  author?: T;
  publishedDate?: T;
  excerpt?: T;
  excerptTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  content?: T;
  contentTranslations?:
    | T
    | {
        de?: T;
        fr?: T;
        nl?: T;
        it?: T;
        es?: T;
        ru?: T;
      };
  image?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trip-configuration_select".
 */
export interface TripConfigurationSelect<T extends boolean = true> {
  name?: T;
  stayTimeInMinutes?: T;
  travelingHoursPerDay?: T;
  defaultStayCost?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-configuration_select".
 */
export interface VehicleConfigurationSelect<T extends boolean = true> {
  vehicleType?: T;
  passengerCount?: T;
  lkrPerKilometer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visiting-places_select".
 */
export interface VisitingPlacesSelect<T extends boolean = true> {
  name?: T;
  latitude?: T;
  longitude?: T;
  stayDuration?: T;
  stayCost?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}